// Coverage reporting with the project's shared exclusion filters, and sets a minimum coverage
// threshold for the module.
import kotlinx.kover.gradle.plugin.dsl.AggregationType
import kotlinx.kover.gradle.plugin.dsl.CoverageUnit

plugins {
    id("org.jetbrains.kotlinx.kover")
}

kover {
    reports {
        filters {
            excludes {
                // Generated bytecode nothing writes by hand, so counting it only depresses the
                // number without naming anything a test could cover.
                classes(
                    "*_Factory",
                    "*_HiltModules*",
                    "*_MembersInjector",
                    "*Hilt_*",
                    "*.ComposableSingletons*",
                    "*.databinding.*",
                    "*.BuildConfig",
                    "*_Impl",
                )
                // Hilt's own aggregation output, which the annotation processor writes into two
                // packages of its own.
                packages(
                    "hilt_aggregated_deps",
                    "dagger.hilt.internal.aggregatedroot.codegen",
                )
                // Android entry points. The framework constructs these, so a JVM test never
                // enters them; the instrumented tests cover them.
                classes(
                    "com.shayan.amro.MainActivity",
                    "com.shayan.amro.AmroApplication",
                    "com.shayan.amro.navigation.AmroAppKt",
                    "com.shayan.amro.navigation.AmroNavDisplayKt*",
                )
                // Hilt modules
                annotatedBy("dagger.Module")
                // Model declarations, whose whole bytecode is the equals, hashCode, copy and
                // toString the compiler writes. A model that grows a body belongs elsewhere.
                packages("com.shayan.amro.core.model")
                // Preview fixtures and galleries. The previews that read them are excluded, so
                // counting the data they hand over measures nothing a test could reach.
                classes("*PreviewData*")
                packages("com.shayan.amro.core.ui.designsystem.preview")
                annotatedBy("androidx.compose.ui.tooling.preview.Preview")
            }
        }

        verify {
            rule {
                // Sets the minimum coverage percentage for the module.
                // The gate fails if the coverage is below this threshold.
                bound {
                    minValue = MIN_LINE_COVERAGE_PERCENT
                    coverageUnits = CoverageUnit.LINE
                    aggregationForGroup = AggregationType.COVERED_PERCENTAGE
                }
            }
        }
    }
}
